const properties = [
    {
        id: "1",
        title: "Modern Oceanfront Villa",
        price: "$4,500,000",
        priceValue: 4500000,
        location: "Malibu, CA",
        beds: 5,
        baths: 6,
        sqft: 6500,
        type: "Villa",
        description: "Experience true luxury in this stunning modern oceanfront villa. Features include an infinity pool, private beach access, and panoramic ocean views from every room.",
        image: "https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?ixlib=rb-4.0.3&auto=format&fit=crop&w=1000&q=80",
        featured: true
    },
    {
        id: "2",
        title: "Skyline Penthouse",
        price: "$2,850,000",
        priceValue: 2850000,
        location: "New York, NY",
        beds: 3,
        baths: 3.5,
        sqft: 3200,
        type: "Penthouse",
        description: "Breathtaking city views from this top-floor penthouse. Custom Italian kitchen, smart home integration, and a private rooftop terrace.",
        image: "https://images.unsplash.com/photo-1512917774080-9991f1c4c750?ixlib=rb-4.0.3&auto=format&fit=crop&w=1000&q=80",
        featured: true
    },
    {
        id: "3",
        title: "Contemporary Hillside Estate",
        price: "$5,200,000",
        priceValue: 5200000,
        location: "Beverly Hills, CA",
        beds: 6,
        baths: 8,
        sqft: 8500,
        type: "House",
        description: "A masterpiece of modern architecture seamlessly blending indoor and outdoor living. Includes a home theater, wine cellar, and guest house.",
        image: "https://images.unsplash.com/photo-1600607687931-cebf1a513028?ixlib=rb-4.0.3&auto=format&fit=crop&w=1000&q=80",
        featured: true
    },
    {
        id: "4",
        title: "Minimalist Desert Retreat",
        price: "$1,750,000",
        priceValue: 1750000,
        location: "Scottsdale, AZ",
        beds: 4,
        baths: 4,
        sqft: 4100,
        type: "House",
        description: "Tranquil desert living in a sleek, minimalist home. Zero-edge pool, extensive outdoor entertainment areas, and spectacular sunset views.",
        image: "https://images.unsplash.com/photo-1600585154340-be6161a56a0c?ixlib=rb-4.0.3&auto=format&fit=crop&w=1000&q=80",
        featured: false
    },
    {
        id: "5",
        title: "Historic Townhouse Renovation",
        price: "$3,100,000",
        priceValue: 3100000,
        location: "Boston, MA",
        beds: 4,
        baths: 3,
        sqft: 2800,
        type: "Townhouse",
        description: "Meticulously restored historic townhouse featuring modern amenities while preserving original architectural details. Private courtyard garden.",
        image: "https://images.unsplash.com/photo-1600566753086-00f18efc2291?ixlib=rb-4.0.3&auto=format&fit=crop&w=1000&q=80",
        featured: false
    },
    {
        id: "6",
        title: "Lakeside Modern Cabin",
        price: "$1,450,000",
        priceValue: 1450000,
        location: "Lake Tahoe, NV",
        beds: 3,
        baths: 2.5,
        sqft: 2200,
        type: "Cabin",
        description: "A modern take on the classic lakeside cabin. Floor-to-ceiling windows, private dock, and environmentally conscious design.",
        image: "https://images.unsplash.com/photo-1518780664697-55e3ad937233?ixlib=rb-4.0.3&auto=format&fit=crop&w=1000&q=80",
        featured: false
    },
    {
        id: "7",
        title: "Sunny Miami Condo",
        price: "$850,000",
        priceValue: 850000,
        location: "Miami, FL",
        beds: 2,
        baths: 2,
        sqft: 1500,
        type: "Condo",
        description: "Beautifully lit condo right in the heart of Miami. Features sweeping ocean views and easy access to vibrant nightlife.",
        image: "https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?ixlib=rb-4.0.3&auto=format&fit=crop&w=1000&q=80",
        featured: false
    },
    {
        id: "8",
        title: "Texas Ranch Retreat",
        price: "$2,200,000",
        priceValue: 2200000,
        location: "Austin, TX",
        beds: 5,
        baths: 4,
        sqft: 5000,
        type: "Ranch",
        description: "Expansive ranch with over 20 acres of land. Features a modern farmhouse design, horse stables, and a large private lake.",
        image: "https://images.unsplash.com/photo-1570129477492-45c003edd2be?ixlib=rb-4.0.3&auto=format&fit=crop&w=1000&q=80",
        featured: true
    },
    {
        id: "9",
        title: "Downtown Luxury Loft",
        price: "$1,250,000",
        priceValue: 1250000,
        location: "Chicago, IL",
        beds: 2,
        baths: 2,
        sqft: 1800,
        type: "Apartment",
        description: "Industrial chic loft in the city center. High ceilings, exposed brick walls, and floor-to-ceiling windows.",
        image: "https://images.unsplash.com/photo-1502005229762-cf1b2da7c5d6?ixlib=rb-4.0.3&auto=format&fit=crop&w=1000&q=80",
        featured: false
    },
    {
        id: "10",
        title: "Cozy Beach House",
        price: "$950,000",
        priceValue: 950000,
        location: "Key West, FL",
        beds: 3,
        baths: 2,
        sqft: 1800,
        type: "Beach house",
        description: "Charming beach house just steps away from the sand. Relaxing wrap-around porch and tropical landscaping.",
        image: "https://images.unsplash.com/photo-1494526585095-c41746248156?ixlib=rb-4.0.3&auto=format&fit=crop&w=1000&q=80",
        featured: false
    },
    {
        id: "11",
        title: "Silicon Valley Tech Home",
        price: "$3,500,000",
        priceValue: 3500000,
        location: "Palo Alto, CA",
        beds: 4,
        baths: 3.5,
        sqft: 3400,
        type: "House",
        description: "Ultra-modern home with state-of-the-art smart home features, energy-efficient design, and a serene Japanese garden.",
        image: "https://images.unsplash.com/photo-1600585154526-990dced4db0d?ixlib=rb-4.0.3&auto=format&fit=crop&w=1000&q=80",
        featured: true
    },
    {
        id: "12",
        title: "Rocky Mountain Chalet",
        price: "$4,100,000",
        priceValue: 4100000,
        location: "Aspen, CO",
        beds: 5,
        baths: 5,
        sqft: 4500,
        type: "Villa",
        description: "Stunning ski-in/ski-out chalet. Features a grand stone fireplace, outdoor hot tub, and spectacular mountain views.",
        image: "https://images.unsplash.com/photo-1542314831-c6a4d1421008?ixlib=rb-4.0.3&auto=format&fit=crop&w=1000&q=80",
        featured: false
    },
    {
        id: "13",
        title: "Suburban Family House",
        price: "$650,000",
        priceValue: 650000,
        location: "Plano, TX",
        beds: 4,
        baths: 2.5,
        sqft: 2600,
        type: "House",
        description: "Perfect family home in a quiet neighborhood. Large backyard, newly renovated kitchen, and close to top-rated schools.",
        image: "https://images.unsplash.com/photo-1580587771525-78b9dba3b914?ixlib=rb-4.0.3&auto=format&fit=crop&w=1000&q=80",
        featured: false
    },
    {
        id: "14",
        title: "Manhattan Luxury Condo",
        price: "$6,200,000",
        priceValue: 6200000,
        location: "New York, NY",
        beds: 3,
        baths: 3,
        sqft: 2800,
        type: "Condo",
        description: "Exclusive condo in a premier luxury building. Offers panoramic Central Park views, 24/7 concierge, and a private spa.",
        image: "https://images.unsplash.com/photo-1512918728675-ed5a9ecdebfd?ixlib=rb-4.0.3&auto=format&fit=crop&w=1000&q=80",
        featured: true
    },
    {
        id: "15",
        title: "Desert Oasis Estate",
        price: "$2,900,000",
        priceValue: 2900000,
        location: "Las Vegas, NV",
        beds: 5,
        baths: 6,
        sqft: 6000,
        type: "House",
        description: "Resort-style living in the desert. Enormous pool with waterfalls, outdoor kitchen, and a full-size tennis court.",
        image: "https://images.unsplash.com/photo-1600607688969-a5bfcd64bd40?ixlib=rb-4.0.3&auto=format&fit=crop&w=1000&q=80",
        featured: false
    },
    {
        id: "16",
        title: "Seattle Waterfront Home",
        price: "$3,800,000",
        priceValue: 3800000,
        location: "Seattle, WA",
        beds: 4,
        baths: 4,
        sqft: 3800,
        type: "House",
        description: "Gorgeous waterfront property offering direct access to the sound. Modern interiors with expansive glass walls.",
        image: "https://images.unsplash.com/photo-1564013799919-ab600027ffc6?ixlib=rb-4.0.3&auto=format&fit=crop&w=1000&q=80",
        featured: false
    },
    {
        id: "17",
        title: "Classic Southern Mansion",
        price: "$4,800,000",
        priceValue: 4800000,
        location: "Charleston, SC",
        beds: 6,
        baths: 7,
        sqft: 7500,
        type: "Villa",
        description: "Historical mansion featuring grand columns, lush gardens, and meticulously preserved antebellum architecture.",
        image: "https://images.unsplash.com/photo-1600047509807-ba8f99d2cdde?ixlib=rb-4.0.3&auto=format&fit=crop&w=1000&q=80",
        featured: false
    },
    {
        id: "18",
        title: "San Francisco Victorian",
        price: "$2,750,000",
        priceValue: 2750000,
        location: "San Francisco, CA",
        beds: 3,
        baths: 2,
        sqft: 2100,
        type: "Townhouse",
        description: "Beautifully updated Victorian home in a prime location. Blends historic charm with modern conveniences.",
        image: "https://images.unsplash.com/photo-1523217582562-09d0def993a6?ixlib=rb-4.0.3&auto=format&fit=crop&w=1000&q=80",
        featured: false
    },
    {
        id: "19",
        title: "Elegant Paris-style Flat",
        price: "$1,850,000",
        priceValue: 1850000,
        location: "Boston, MA",
        beds: 2,
        baths: 2,
        sqft: 1600,
        type: "Apartment",
        description: "Sophisticated flat featuring ornate moldings, herringbone floors, and a balcony overlooking a historic square.",
        image: "https://images.unsplash.com/photo-1493809842364-78817add7ffb?ixlib=rb-4.0.3&auto=format&fit=crop&w=1000&q=80",
        featured: false
    },
    {
        id: "20",
        title: "Hollywood Hills Mansion",
        price: "$8,500,000",
        priceValue: 8500000,
        location: "Los Angeles, CA",
        beds: 5,
        baths: 7,
        sqft: 8000,
        type: "Villa",
        description: "Ultimate luxury living in the Hollywood Hills. Features an infinity edge pool, private cinema, and sweeping city views.",
        image: "https://images.unsplash.com/photo-1512915922686-57c11dde9b6b?ixlib=rb-4.0.3&auto=format&fit=crop&w=1000&q=80",
        featured: true
    }
];

// If using ES modules
if (typeof module !== 'undefined' && module.exports) {
    module.exports = properties;
}
